### ISSUE TITLE
Installing error 

### ISSUE THREAD

**Issue by ehsandeep** [mazen160/bfac#7]
while installing i see this reason, and i don't get the reason, can you figure it out why it's happening.
 
````
root@vps:~/bfac# sudo python setup.py install
running install
running bdist_egg
running egg_info
creating bfac.egg-info
writing requirements to bfac.egg-info/requires.txt
writing bfac.egg-info/PKG-INFO
writing top-level names to bfac.egg-info/top_level.txt
writing dependency_links to bfac.egg-info/dependency_links.txt
writing manifest file 'bfac.egg-info/SOURCES.txt'
reading manifest file 'bfac.egg-info/SOURCES.txt'
writing manifest file 'bfac.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bfac -> build/scripts-2.7
changing mode of build/scripts-2.7/bfac from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/bfac -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/bfac to 755
copying bfac.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bfac.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bfac.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bfac.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bfac.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/bfac-1.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bfac-1.3-py2.7.egg
Copying bfac-1.3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding bfac 1.3 to easy-install.pth file
Installing bfac script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/bfac-1.3-py2.7.egg
Processing dependencies for bfac==1.3
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    license='GPL-3.0'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 617, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 645, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2409, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.4.3 has no such extra feature 'socks'
````

**Comment by mazen160** [comment]
That's an odd. Probably you're using an old version of Python that does not support `requests[socks]`.

Maybe try updating your current Python2 build, or install it via Python3.

`sudo python3 setup.py install`

**Comment by kranthikurapati** [comment]
Same error when using python3.8.10 as well
